Section A: Data Types & Control Flow (Q1–Q15)

In [114]:
# 1. Write a Python program to find the second largest number in a list without using the sort() method.

In [122]:
def find_second_largest_number(nums):
    nums = list(set(nums))
    if len(nums) > 2:
        largest = max(nums)
        nums.remove(largest)
        second_largest = max(nums)
        return second_largest

user_input = input()
nums = list(map(int, user_input.split()))
second_largest = find_second_largest_number(nums)
print(second_largest)

 4 5 3 5 6 7


6


In [116]:
# 2. Remove duplicates from a list without using set() and return it in sorted order.

In [124]:
def remove_duplicates_and_sort(nums):
    result = []
    for num in nums:
        if num not in result:
            result.append(num)
            
    result.sort()
    return result

user_input = input()
nums = list(map(int, user_input.split()))
result = remove_duplicates_and_sort(nums)
print(result)

 4 5 3 3 5 6 7


[3, 4, 5, 6, 7]


In [118]:
# 3. Find the sum and average of a list of numbers.

In [125]:
def sum_of_numbers(nums):
    nums_sum = sum(nums)
    return nums_sum
    
def average_of_numbers(numbers):
    nums_avg = sum(nums) / len(nums)
    return nums_avg

user_input = input()
nums = list(map(int, user_input.split()))
nums_sum = sum_of_numbers(nums)
nums_avg = average_of_numbers(nums)
print(nums_sum)
print(nums_avg)

 4 5 7 3 2 5 6


32
4.571428571428571


In [ ]:
# 4. Create a program to check if a number is prime.

In [126]:
def is_prime_number(num):
    count = 0;
    if num > 1:
        for n in range(2, num // 2 + 1):
            if num % n == 0:
                count+=1

        if count > 0:
            return "Not a prime number."
        else:
            return "Prime Number"

num = int(input())
result = is_prime_number(num)
print(result)

 5


Prime Number


In [ ]:
# 5. Count the number of vowels, consonants, digits, and special characters in a given string.

In [127]:
def count_vowels(string):
    vowels = 0
    for char in string:
        if char.isalpha():
            if char.lower() in 'aeiou':
                vowels += 1
                
    return vowels
    
def count_consonants(string):
    consonants = 0
    for char in string:
        if char.isalpha():
            if char.lower() not in 'aeiou':
                consonants += 1
                
    return consonants
    
def count_digits(string):
    digits = 0
    for char in string:
        if char.isdigit():
            digits += 1
            
    return digits
    
def count_special_characters(string):
    special_characters = 0
    for char in string:
        if not char.isalpha() and not char.isdigit():
            special_characters += 1
            
    return special_characters

string = input()
vowels = count_vowels(string)
consonants = count_consonants(string)
digits = count_digits(string)
special_characters = count_special_characters(string)
# Display results
print(vowels)
print(consonants)
print(digits)
print(special_characters)

 He110, H0w R y0u? 


2
5
5
6


In [ ]:
# 6. Print all even numbers between 1 and 100 using a for loop.

In [128]:
def even_numbers(num):
    for n in range(2, num+1, 2):
        print(n)

even_numbers(100)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
# 7. Write a program to print the multiplication table of a number entered by the user.

In [129]:
def multiplication_table_of_a_number(num):
    for n in range(1, 11):
        print(num, 'x', n, '=', num * n)

num = int(input())
multiplication_table_of_a_number(num)

 7


7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70


In [ ]:
# 8. Create a list of numbers from 1 to 100 that are divisible by both 3 and 5.

In [130]:
# Create the list using a list comprehension
def create_a_list_of_numbers_divisible_by_3_and_5(num):
    nums_divisible_by_3_and_5 = [n for n in range(1, num+1) if n % 3 == 0 and n % 5 == 0]
    return nums_divisible_by_3_and_5

nums = create_a_list_of_numbers_divisible_by_3_and_5(100)
print(nums)

[15, 30, 45, 60, 75, 90]


In [ ]:
# 9. Take a number input and print its reverse.

In [131]:
def reverse_of_a_number(num):
    reversed_num = num[::-1]
    return int(reversed_num)

num = input()
reversed_num = reverse_of_a_number(num)
print(reversed_num)

 657


756


In [ ]:
# 10. Count the frequency of each character in a string and store it in a dictionary.

In [132]:
def create_a_dictionary(string):
    char_frequency_dictionary = {}
    for char in string:
        if char in char_frequency_dictionary:
            char_frequency_dictionary[char] += 1
        else:
            char_frequency_dictionary[char] = 1

    return char_frequency_dictionary

string = input()
char_frequency_dictionary = create_a_dictionary(string)
print(char_frequency_dictionary)

 Hello, How are you?


{'H': 2, 'e': 2, 'l': 2, 'o': 3, ',': 1, ' ': 3, 'w': 1, 'a': 1, 'r': 1, 'y': 1, 'u': 1, '?': 1}


In [ ]:
# 11. Write a Python program to generate the first n prime numbers.

In [133]:
def is_prime_number(num):
    count = 0;
    if num > 1:
        for n in range(2, num // 2 + 1):
            if num % n == 0:
                count+=1

        if count > 0:
            return False
        else:
            return True

def generate_n_prime_numbers(n):
    prime_nums = []
    num = 2
    while len(prime_nums) < n:
        if is_prime_number(num):
            prime_nums.append(num)
        num += 1
    return prime_nums

n = int(input())
prime_nums = generate_n_prime_numbers(n)
print(prime_nums)

 9


[2, 3, 5, 7, 11, 13, 17, 19, 23]


In [ ]:
# 12. Check whether a number is a palindrome or not.

In [134]:
def is_palindrome_number(num):
    if num == num[::-1]:
        return "Palindrome Number."
    else:
        return "Not a Palindrome Number."

num = input()
result = is_palindrome_number(num)
print(result)

 56465


Palindrome Number.


In [ ]:
# 13. Count how many times a specific element appears in a list.

In [135]:
def count_a_element(target_elem, elems):
    count = elems.count(target_elem)
    return count
    
user_input = input()
elems = user_input.split()
target_elem = input()
result = count_a_element(target_elem, elems)
print(result)

 hello how are you
 you


1


In [ ]:
# 14. Create a list of squares of even numbers between 1 and 50.

In [136]:
def create_a_list_of_squares_of_even_numbers(num):
    squares_of_even_nums = [n**2 for n in range(2, num, 2)]
    return squares_of_even_nums

num = 50
squares_of_even_nums = create_a_list_of_squares_of_even_numbers(num)
print(squares_of_even_nums)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304]


In [ ]:
# 15. Accept a list and return a new list with only unique elements (preserve order).

In [137]:
def get_unique_elements(elems):
    unique_elems = []
    for elem in elems:
        if elem not in unique_elems:
            unique_elems.append(elem)
            
    return unique_elems

user_input = input()
elems = user_input.split()
unique_elems = get_unique_elements(elems)
print(unique_elems)

 hello hello okk fine okk nice


['hello', 'okk', 'fine', 'nice']


Section B: Functions (Q16–Q30)

In [ ]:
# 16. Write a function to check if a number is even or odd.

In [138]:
def check_even_number_or_odd_number(num):
    if num % 2 == 0:
        return "Even Number"
    else:
        return "Odd Number"

num = int(input())
result = check_even_number_or_odd_number(num)
print(result)

 7


Odd Number


In [ ]:
# 17. Create a function that takes a list of numbers and returns their cumulative sum.

In [139]:
def cumulative_sum_of_numbers(nums):
    result = []
    cumulative_sum = 0
    for num in nums:
        cumulative_sum += num
        result.append(cumulative_sum)
        
    return result

user_input = input()
nums = list(map(int, user_input.split()))
result = cumulative_sum_of_numbers(nums)
print(result)

 4 6 4 3 6 7 4 2 0


[4, 10, 14, 17, 23, 30, 34, 36, 36]


In [ ]:
# 18. Write a recursive function to find the factorial of a number.

In [140]:
def factorial_of_a_number(num):
    if num == 0 or num == 1:
        return 1
    else:
        return num * factorial_of_a_number(num - 1)

num = int(input())
result = factorial_of_a_number(num)
print(result)

 5


120


In [ ]:
# 19. Write a function to print the Fibonacci series up to n terms.

In [141]:
def fibonacci_series(n):
    a, b = 0, 1
    for i in range(n):
        print(a, end=' ')
        a, b = b, a + b

n = int(input())
fibonacci_series(n)

 7


0 1 1 2 3 5 8 

In [ ]:
# 20. Define a function that checks if a given string is a palindrome.

In [143]:
def is_palindrome_string(string):
    string = string.lower()
    if string == string[::-1]:
        return "Palindrome String"
    else:
        return "Not a Palindrome String"

string = input()
result = is_palindrome_string(string)
print(result)

 Lemon O Nomel


Palindrome String


In [ ]:
# 21. Create a function that returns the maximum and minimum elements from a list.

In [145]:
def find_max_number_and_min_number(nums):
    max_num = min_num = nums[0]
    for num in nums[1:]:
        if num > max_num:
            max_num = num
        elif num < min_num:
            min_num = num
    return max_num, min_num

# Example usage
user_input = input()
nums = list(map(int, user_input.split()))

max_num, min_num = find_max_number_and_min_number(nums)
print(max_num, min_num)

 5 6 3 7 4 1 7 8 8 5 3 


8 1


In [ ]:
# 22. Write a function to check whether a string is a pangram.

In [146]:
import string

def is_pangram_string(string_text):
    string_text = string_text.lower()
    alphas = set(string.ascii_lowercase)
    if alphas.issubset(set(string_text)):
        return "Pangram String"
    else:
        return "Not a Pangram String"

string_text = input()
result = is_pangram_string(string_text)
print(result)

 The quick brown fox jumps over the lazy dog


Pangram String


In [ ]:
# 23. Create a function that finds and returns all prime numbers in a given range.

In [147]:
def generate_prime_numbers_in_a_range(start_num, end_num):
    def is_prime_number(num):
        count = 0;
        if num > 1:
            for n in range(2, num // 2 + 1):
                if num % n == 0:
                    count+=1

            if count > 0:
                return False
            else:
                return True
            
    prime_nums = []
    num = start_num
    while num < end_num:
        if is_prime_number(num):
            prime_nums.append(num)
        num += 1
    return prime_nums

start_num = int(input())
end_num = int(input())
prime_nums = generate_prime_numbers_in_a_range(start_num, end_num)
print(prime_nums)

 45
 78


[47, 53, 59, 61, 67, 71, 73]


In [ ]:
# 24. Write a function to return the number of uppercase and lowercase letters in a string.

In [148]:
def count_uppercase_and_lowercase_letters(string_text):
    uppercase_letters_count = 0
    lowercase_letters_count = 0
    for char in string_text:
        if char.isupper():
            uppercase_letters_count += 1
        elif char.islower():
            lowercase_letters_count += 1

    return uppercase_letters_count, lowercase_letters_count

string_text = input()
uc_count, lc_count = count_uppercase_and_lowercase_letters(string_text)
print(uc_count, lc_count)

 Hello Wolrd mY wElcome


4 15


In [ ]:
# 25. Write a function to compute the sum of digits of a number.

In [149]:
def sum_of_digits_of_a_number(num):
    sum_of_digits = 0
    while num > 0:
        sum_of_digits += num % 10
        num //= 10
    return sum_of_digits

num = int(input())
sum_of_digits = sum_of_digits_of_a_number(num)
print(sum_of_digits)

 46383


24


In [ ]:
# 26. Write a function to count words in a sentence.

In [150]:
def count_words_in_a_sentence(sentence):
    words_count = sentence.split()
    return len(words_count)

sentence = input()
words_count = count_words_in_a_sentence(sentence)
print(words_count)

 Hello My name is World What about you


8


In [ ]:
# 27. Create a function to remove all punctuation from a string.

In [151]:
import string

def remove_all_punctuation_from_a_string(string_text):
    result = [char for char in string_text if char not in string.punctuation]
    return ''.join(result)

string_text = input()
result = remove_all_punctuation_from_a_string(string_text)
print(result)

 Hello, How are you? its Okay.


Hello How are you its Okay


In [ ]:
# 28. Create a function that finds the GCD (greatest common divisor) of two numbers.

In [152]:
def find_gcd_of_two_nums(num1, num2):
    while num2 != 0:
        num1, num2 = num2, num1 % num2
    return num1

num1 = int(input())
num2 = int(input())
result = find_gcd_of_two_nums(num1, num2)
print(result)

 45
 70


5


In [ ]:
# 29. Write a function that takes a list and returns only those elements that appear more than once.

In [154]:
def find_duplicative_elements(elems):
    unique_elems = list(set(elems))
    duplicate_elems = []
    for elem in unique_elems:
        if elems.count(elem) > 1:
            duplicate_elems.append(elem)
            
    return duplicate_elems

user_input = input()
elems = user_input.split()
duplicate_elems = find_duplicative_elements(elems)
print(duplicate_elems)

 hello one hello two to hello three hell to


['to', 'hello']


In [ ]:
# 30. Create a function to return the largest of three numbers.

In [156]:
def largest_of_three_numbers(num1, num2, num3):
    if num1 >= num2 and num1 >= num3:
        return num1
    elif num2 >= num1 and num2 >= num3:
        return num2
    else:
        return num3

num1 = int(input())
num2 = int(input())
num3 = int(input())
largest_num = largest_of_three_numbers(num1, num2, num3)
print(largest_num)

 45
 34
 25


45


Section C: String, List, Dictionary & Tuple Operations (Q31–Q40)

In [ ]:
# 31. Write a program to sort words in a sentence alphabetically.

In [160]:
def sort_words_in_a_sentence(sentence):
    words = sentence.split()
    words.sort()
    return ' '.join(words)

sentence = input()
sorted_sentence = sort_words_in_a_sentence(sentence)
print(sorted_sentence)

 hello sigma hey hi alpha how are you


alpha are hello hey hi how sigma you


In [ ]:
# 32. Concatenate two dictionaries and print the result.

In [161]:
def concatenate_two_dictionaries(dict1, dict2):
    result = dict1.copy()
    result.update(dict2)
    return result

user_input_1 = input()
dict1 = dict(map(lambda item: item.split(':'), user_input_1.split()))
user_input_2 = input()
dict2 = dict(map(lambda item: item.split(':'), user_input_2.split()))
result = concatenate_two_dictionaries(dict1, dict2)
print(result)

 name:John age:35 hometown:Bellwood
 hobby:singing profession:doctor


{'name': 'John', 'age': '35', 'hometown': 'Bellwood', 'hobby': 'singing', 'profession': 'doctor'}


In [ ]:
# 33. Count how many vowels are present in each word of a sentence.

In [162]:
def count_vowels_in_each_word(sentence):
    def count_vowels(word):
        count = 0
        for char in word:
            if char.lower() in 'aeiou':
                count += 1
        return count

    words_dictionary = {}
    words = sentence.split()
    for word in words:
        words_dictionary[word] = count_vowels(word)
    return words_dictionary

sentence = input()
words_dictionary = count_vowels_in_each_word(sentence)
print(words_dictionary)

 hello how are you


{'hello': 2, 'how': 1, 'are': 2, 'you': 2}


In [ ]:
# 34. Accept a tuple and convert it into a list.

In [163]:
def convert_tuple_to_list(tuple_input):
    list_output = list(tuple_input)
    return list_output
    
user_input = input()
tuple_input = tuple(user_input.split())
list_output = convert_tuple_to_list(tuple_input)
print(list_output)

 hello how are you its fine okk


['hello', 'how', 'are', 'you', 'its', 'fine', 'okk']


In [ ]:
# 35. Remove all whitespace from a given string using a function.

In [164]:
def remove_all_whitespace_from_a_string(string_text):
    return ''.join(string_text.split())

string_text = input()
result = remove_all_whitespace_from_a_string(string_text)
print(result)

 hello i am here going for party


helloiamheregoingforparty


In [ ]:
# 36. Merge two lists into a dictionary using one as keys and the other as values.

In [165]:
def merge_two_lists_to_a_dictionary(keys, values):
    merged_dictionary = {}
    for i in range(len(keys)):
        merged_dictionary[keys[i]] = values[i]
    return merged_dictionary

keys = input().split()
values = input().split()
merged_dictionary = merge_two_lists_to_a_dictionary(keys, values)
print(merged_dictionary)

 name age profession
 John 35 Doctor


{'name': 'John', 'age': '35', 'profession': 'Doctor'}


In [ ]:
# 37. Write a program to get the key with the maximum value in a dictionary.

In [166]:
def key_with_maximum_value(dict_input):
    return max(dict_input, key=dict_input.get)

dict_input = dict(map(lambda item: (item.split(':')[0], int(item.split(':')[1])), input().split()))
resultant_key = key_with_maximum_value(dict_input)
print(resultant_key)

 num1:54 num2:56 num3:23 num4:78 num5:03


num4


In [ ]:
# 38. Accept a string and print a dictionary with word frequencies.

In [167]:
def word_frequency_in_a_sentence(sentence):
    words = sentence.split()
    unique_words = set(words)
    result = {}
    for unique_word in unique_words:
        result[unique_word] = words.count(unique_word)
    return result

sentence = input()
result = word_frequency_in_a_sentence(sentence)
print(result)

 Hello how are you hello i am fine


{'are': 1, 'how': 1, 'i': 1, 'am': 1, 'Hello': 1, 'hello': 1, 'you': 1, 'fine': 1}


In [ ]:
# 39. Write a program to check if a key exists in a dictionary.

In [168]:
def check_key_existence(target_key, dict_input):
    if target_key in dict_input:
        return "Key exists"
    else:
        return "Key not exist"

dict_input = dict(map(lambda item: item.split(':'), input().split()))
target_key = input()
result = check_key_existence(target_key, dict_input)
print(result)

 name:John age:35 profession:Dcotor hobby:Singing
 hobby


Key exists


In [ ]:
# 40. Write a program to replace all the vowels in a string with '*'.

In [169]:
def replace_vowels_with_asterisk(string_input):
    vowels = 'aeiouAEIOU'
    resultant_string = ''
    for char in string_input:
        if char in vowels:
            resultant_string += '*'
        else:
            resultant_string += char
    return resultant_string

string_input = input()
resultant_string = replace_vowels_with_asterisk(string_input)
print(resultant_string)

 HellO, how are you?


H*ll*, h*w *r* y**?


Section D: File Handling (Q41–Q45)

In [ ]:
# 41. Write a Python program to read the contents of a file and display it.

In [170]:
def read_contents_of_a_file(filename):
    with open(filename, 'r') as file:
        file_content = file.read()
        return file_content

filename = input()
file_content = read_contents_of_a_file(filename)
print(file_content)

 Numpy.ipynb


{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 278,
   "id": "df1b0c81-1f8b-4fcc-a1b4-d5833637b6bb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 279,
   "id": "0b623e8c-3d68-4738-bd1a-fbe36397f487",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1 2 3 4]\n"
     ]
    }
   ],
   "source": [
    "# 1D array\n",
    "a = np.array([1, 2, 3, 4]) # [1, 2, 3, 4] is a vector array\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 280,
   "id": "bd8633a3-5185-4a1f-a04d-f0ba45129955",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1, 2, 3, 4])"
      ]
     },
     "execution_count": 280,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "a"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 281,


In [ ]:
# 42. Count the number of words in a file.

In [171]:
def count_number_of_words_in_a_file(filename):
    with open(filename, 'r') as file:
        file_content = file.read()
        words = file_content.split()
        return len(words)

filename = input()
words_count = count_number_of_words_in_a_file(filename)
print(words_count)

 Numpy.ipynb


3689


In [ ]:
# 43. Copy contents of one file to another.

In [172]:
def copy_file_contents(source_filename, destination_filename):
        with open(source_filename, 'r') as source_file:
            content = source_file.read()
        with open(destination_filename, 'w') as destination_file:
            destination_file.write(content)
        return "File contents copied."

source_filename = input()
destination_filename = input()
result = copy_file_contents(source_filename, destination_filename)
print(result)

 Numpy.ipynb
 Numpy-copy.ipynb


File contents copied.


In [ ]:
# 44. Print only the lines that have more than 50 characters from a text file.

In [173]:
def print_lines_of_more_than_50_characters(filename):
    with open(filename, 'r') as file:
        for line in file:
            if len(line.strip()) > 50:
                print(line.strip())

filename = input()
print_lines_of_more_than_50_characters(filename)

 Numpy.ipynb


"a = np.array([1, 2, 3, 4]) # [1, 2, 3, 4] is a vector array\n",
"b = np.array([[1, 2, 3], [4, 5, 6]]) # [[1, 2, 3], [4, 5, 6]] is a matrix array\n",
"c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] is a tensor array\n",
"array([[0.38082135, 0.29585101, 0.24420592, 0.17544694],\n",
"       [0.67451045, 0.44143713, 0.29176129, 0.29803281],\n",
"       [0.21112547, 0.39400114, 0.71560774, 0.78026727]])"
"array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,\n",
"        -1.11111111,   1.11111111,   3.33333333,   5.55555556,\n",
"array([0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9])"
"array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,\n",
"       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,\n",
"       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,\n",
"       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])"
"array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.894

In [ ]:
# 45. Write a program to write a list of strings into a text file (one string per line).

In [174]:
def write_list_of_strings_into_text_file(strings_input, filename):
    with open(filename, 'w') as file:
        for string_input in strings_input:
            file.write(string_input + '\n')
    return "File contents written successfully."

strings_input = input().split(',')
filename = input()
result = write_list_of_strings_into_text_file(strings_input, filename)
print(result)

 Hello,World,Excuse Me,How are you?
 Output.txt


File contents written successfully.


Section E: Exception Handling (Q46–Q50)

In [ ]:
# 46. Write a program to take two numbers as input and handle division by zero.

In [175]:
def divide_one_number_by_another(num1, num2):
    try:
        result = num1 / num2
        return result
    except ZeroDivisionError:
        return "Error: Cannot divide by zero."

num1 = int(input())
num2 = int(input())
result = divide_one_number_by_another(num1, num2)
print(result)

 5
 0


Error: Cannot divide by zero.


In [ ]:
# 47. Handle invalid user input (e.g., entering a string when a number is expected).

In [176]:
def check_user_input():
    try:
        user_input = int(input())
        print("Input handled successfully.")
    except ValueError:
        print("Invalid input! Please enter a integer number.")
        check_user_input()

check_user_input()

 hello


Invalid input! Please enter a integer number.


 hi


Invalid input! Please enter a integer number.


 5.6


Invalid input! Please enter a integer number.


 5


Input handled successfully.


In [ ]:
# 48. Try to open a file that doesn’t exist and handle the FileNotFoundError.

In [177]:
def open_a_file(filename):
    try:
        with open(filename, 'r') as file:
            content = file.read()
            return "File handled successfully."
    except FileNotFoundError:
        return "Error: File not found!"

filename = input()
result = open_a_file(filename)
print(result)

 Numpy.txt


Error: File not found!


In [ ]:
# 49. Create a list of numbers and try accessing an invalid index. Handle the exception gracefully.

In [178]:
def handle_list_of_numbers(lsit_input, indx):
    try:
        if list_input[indx]:
            return "Index handled successfully."
    except IndexError:
        return "Error: Invalid index!"

list_input = list(map(int, input().split()))
indx = int(input())
result = handle_list_of_numbers(list_input, indx)
print(result)

 4 5 7 4 3 2 0 1
 9


Error: Invalid index!


In [ ]:
# 50. Use a try-except-finally block to demonstrate the execution of the finally clause.

In [179]:
def demonstate_finally_clause_execution():
    try:
        num1 = int(input())
        num2 = int(input())
        result = num1 / num2
        print("try clause executed successfully.")
    except ZeroDivisionError:
        print("except clause executed successfully.")
    finally:
        print("finally clause executed successfully.")
        
demonstate_finally_clause_execution()

 5
 0


except clause executed successfully.
finally clause executed successfully.
